export const SKILLS_REPORT_FORM_UNFOLD = 'SKILLS_REPORT_FORM_UNFOLD'
export const SKILLS_REPORT_FORM_ADD_SKILL = 'SKILLS_REPORT_FORM_ADD_SKILL'
export const SKILLS_REPORT_FORM_REMOVE_SKILL = 'SKILLS_REPORT_FORM_REMOVE_SKILL'
export const SKILLS_REPORT_FORM_CLEAR_ERROR = 'SKILLS_REPORT_FORM_CLEAR_ERROR'
export const SKILLS_REPORT_FORM_REQUEST = 'SKILLS_REPORT_FORM_REQUEST'
export const SKILLS_REPORT_FORM_SUCCESS = 'SKILLS_REPORT_FORM_SUCCESS'
export const SKILLS_REPORT_FORM_FAILURE = 'SKILLS_REPORT_FORM_FAILURE'

export const USER_ADD_USED_SKILLS = 'USER_ADD_USED_SKILLS'
export const USER_SKILLS_INCREMENT = 'USER_SKILLS_INCREMENT'
export const USER_SET_USED_ALL_SKILL_POINTS = 'USER_SET_USED_ALL_SKILL_POINTS'
export const USER_UPDATE = 'USER_UPDATE'

export const SKILLS_SET_ACTIVE_GROUP = 'SKILLS_SET_ACTIVE_GROUP'
export const SKILL_SELECT = 'SKILL_SELECT'

export const SKILL_DETAILS_FORM_REQUEST = 'SKILL_DETAILS_FORM_REQUEST'
export const SKILL_DETAILS_FORM_SUCCESS = 'SKILL_DETAILS_FORM_SUCCESS'
export const SKILL_DETAILS_FORM_FAILURE = 'SKILL_DETAILS_FORM_FAILURE'
